--CREATE TABLE IF NOT EXISTS POST(
--    post_id INT AUTO_INCREMENT PRIMARY KEY,
--    title VARCHAR (255) NOT NULL,
--    user_name VARCHAR (255) NOT NULL,
--    content VARCHAR (255) NOT NULL
--);
;